[package]
name = "shifter"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

# Used for differential fuzz testing
[dev-dependencies]
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
rayon = "1.10.0"
